openapi: 3.0.1
info:
  title: IterateUsers
  description: API Definition of IterateUsers
  version: 1.0.0
servers:
- url: http://localhost:8290/users
paths:
  /:
    post:
      responses:
        default:
          description: Default response
