openapi: 3.0.1
info:
  title: Iter_API
  description: API Definition of Iter_API
  version: 1.0.0
servers:
- url: http://localhost:8290/itr
paths:
  /:
    post:
      responses:
        default:
          description: Default response
