openapi: 3.0.1
info:
  title: Fake_API
  description: API Definition of Fake_API
  version: 1.0.0
servers:
- url: http://localhost:8290/fake
paths:
  /:
    post:
      responses:
        default:
          description: Default response
